
CREATE TABLE subasta(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL, 
    description VARCHAR(255),
    status BOOLEAN NOT NULL DEFAULT 0, 
    createAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
)

CREATE TABLE usuarios(
    pk_id INTEGER PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    gmail VARCHAR(255) NOT NULL, 
    password VARCHAR(255) NOT NULL
)