import React from "react";

const users = [
  {
    identificacion: 1,
    nombre: "Tony Reichert",
    rol: "CEO",
    team: "Mantelefonoment",
    estado: "activo",
    telefono: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    identificacion: 2,
    nombre: "Zoey Lang",
    rol: "Tech Lead",
    team: "Development",
    estado: "inactivo",
    telefono: "25",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "zoey.lang@example.com",
  },
  {
    identificacion: 3,
    nombre: "Jane Fisher",
    rol: "Sr. Dev",
    team: "Development",
    estado: "activo",
    telefono: "22",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "jane.fisher@example.com",
  },
  {
    identificacion: 4,
    nombre: "William Howard",
    rol: "C.M.",
    team: "Marketing",
    estado: "activo",
    telefono: "28",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    email: "william.howard@example.com",
  },
  {
    identificacion: 5,
    nombre: "Kristen Copper",
    rol: "S. Mantelefonor",
    team: "Sales",
    estado: "activo",
    telefono: "24",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "kristen.cooper@example.com",
  },
  {
    identificacion: 6,
    nombre: "Brian Kim",
    rol: "P. Mantelefonor",
    team: "Mantelefonoment",
    telefono: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "brian.kim@example.com",
    estado: "activo",
  },
  {
    identificacion: 7,
    nombre: "Michael Hunt",
    rol: "Designer",
    team: "Design",
    estado: "inactivo",
    telefono: "27",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
    email: "michael.hunt@example.com",
  },
  {
    identificacion: 8,
    nombre: "Samantha Brooks",
    rol: "HR Mantelefonor",
    team: "HR",
    estado: "activo",
    telefono: "31",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
    email: "samantha.brooks@example.com",
  },
  {
    identificacion: 9,
    nombre: "Frank Harrison",
    rol: "F. Mantelefonor",
    team: "Finance",
    estado: "activo",
    telefono: "33",
    avatar: "https://i.pravatar.cc/150?img=4",
    email: "frank.harrison@example.com",
  },
  {
    identificacion: 10,
    nombre: "Emma Adams",
    rol: "Ops Mantelefonor",
    team: "Operations",
    estado: "activo",
    telefono: "35",
    avatar: "https://i.pravatar.cc/150?img=5",
    email: "emma.adams@example.com",
  },
  {
    identificacion: 11,
    nombre: "Brandon Stevens",
    rol: "Jr. Dev",
    team: "Development",
    estado: "activo",
    telefono: "22",
    avatar: "https://i.pravatar.cc/150?img=8",
    email: "brandon.stevens@example.com",
  },
  {
    identificacion: 12,
    nombre: "Megan Richards",
    rol: "P. Mantelefonor",
    team: "Product",
    estado: "inactivo",
    telefono: "28",
    avatar: "https://i.pravatar.cc/150?img=10",
    email: "megan.richards@example.com",
  },
  {
    identificacion: 13,
    nombre: "Oliver Scott",
    rol: "S. Mantelefonor",
    team: "Security",
    estado: "activo",
    telefono: "37",
    avatar: "https://i.pravatar.cc/150?img=12",
    email: "oliver.scott@example.com",
  },
  {
    identificacion: 14,
    nombre: "Grace Allen",
    rol: "M. Specialist",
    team: "Marketing",
    estado: "activo",
    telefono: "30",
    avatar: "https://i.pravatar.cc/150?img=16",
    email: "grace.allen@example.com",
  },
  {
    identificacion: 15,
    nombre: "Noah Carter",
    rol: "IT Specialist",
    team: "I. Technology",
    estado: "inactivo",
    telefono: "31",
    avatar: "https://i.pravatar.cc/150?img=15",
    email: "noah.carter@example.com",
  },
  {
    identificacion: 16,
    nombre: "Ava Perez",
    rol: "Mantelefonor",
    team: "Sales",
    estado: "activo",
    telefono: "29",
    avatar: "https://i.pravatar.cc/150?img=20",
    email: "ava.perez@example.com",
  },
  {
    identificacion: 17,
    nombre: "Liam Johnson",
    rol: "Data Analyst",
    team: "Analysis",
    estado: "activo",
    telefono: "28",
    avatar: "https://i.pravatar.cc/150?img=33",
    email: "liam.johnson@example.com",
  },
  {
    identificacion: 18,
    nombre: "Sophia Taylor",
    rol: "QA Analyst",
    team: "Testing",
    estado: "activo",
    telefono: "27",
    avatar: "https://i.pravatar.cc/150?img=29",
    email: "sophia.taylor@example.com",
  },
  {
    identificacion: 19,
    nombre: "Lucas Harris",
    rol: "Administrator",
    team: "Information Technology",
    estado: "inactivo",
    telefono: "32",
    avatar: "https://i.pravatar.cc/150?img=50",
    email: "lucas.harris@example.com",
  },
  {
    identificacion: 20,
    nombre: "Mia Robinson",
    rol: "Coordinator",
    team: "Operations",
    estado: "activo",
    telefono: "26",
    avatar: "https://i.pravatar.cc/150?img=45",
    email: "mia.robinson@example.com",
  },
];

export { users };
